[package]
name = "transmission-client"
version = "0.1.0"
authors = ["Felix HÃ¤cker <haeckerfelix@gnome.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
