[package]
name = "transmission-client"
version = "0.1.0"
authors = ["Felix HÃ¤cker <haeckerfelix@gnome.org>"]
edition = "2018"
description = "WIP"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.125"
serde_json = "1.0.64"
serde_derive = "1.0.125"
url = { version = "2.2.1", features = ["serde"] }
log = "0.4.14"
isahc = "1.3.1"
thiserror = "1.0.24"
